version: '3.8'

services:
  backend:
    container_name: d1-backend
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - app-network

  frontend:
    container_name: d1-frontend
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "800:800"
    depends_on:
      - backend 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
